# AWS Build Specification

version: 0.2

env:
  variables:
    DB_HOST: "localhost"
    DB_NAME: postgresql
    DB_USER: lukefitzgerald
    DB_PORT: 5432
    DB_PASSWORD: "this-is-a-temporary-password-and-is-not-sensitive"
    ENVIRONMENT: "DEV"
    NODEVERSION: "8.15.0"

phases:
  install:
    runtime-versions:
      nodejs: 8.15.0

    commands:
      - echo Installing sudo
      - apt-get install sudo -y
      - echo Installing NodeJS
      - sudo mkdir /usr/local/lib/nodejs
      - "wget -q https://nodejs.org/download/release/v${NODEVERSION}/node-v${NODEVERSION}-linux-x64.tar.xz"
      - 'sudo tar -xJf "node-v${NODEVERSION}-linux-x64.tar.xz" -C /usr/local/lib/nodejs'
      - "sudo rm -f node-v${NODEVERSION}-linux-x64.tar.xz"
      - "sudo mv /usr/local/lib/nodejs/node-v${NODEVERSION}-linux-x64 /usr/local/lib/nodejs/node-v${NODEVERSION}"
      - NODEJS_HOME="/usr/local/lib/nodejs/node-v${NODEVERSION}"
      - PATH=$NODEJS_HOME/bin:$PATH
      - node -v
      - npm --version
      - rm -f ~/.npmrc
  build:
    commands:
      - echo "Running Build step"
      - echo Install NPM Packages
      - echo "unsafe-perm=true" >> .npmrc
      - npm install >/dev/null

  post_build:
    commands:
      - echo Running post-build commands
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
