# AWS Build Specification

version: 0.2

env:
  variables:
    DB_HOST: "localhost"
    DB_NAME: postgresql
    DB_USER: lukefitzgerald
    DB_PORT: 5432
    DB_PASSWORD: "this-is-a-temporary-password-and-is-not-sensitive"
    ENVIRONMENT: "DEV"
    NODEVERSION: "8.15.0"

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - echo Starting the Install phase
      - node --version
      - npm --version
      - pwd

  build:
    commands:
      - echo "Running Build step"
      - echo Install NPM Packages
      - echo "unsafe-perm=true" >> .npmrc
      - npm install

  post_build:
    commands:
      - echo Running post-build commands
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
