# AWS Build Specification

version: 0.2

env:
  variables:
    DB_HOST: "DB_HOST"
    DB_NAME: "DB_NAME"
    DB_USER: "DB_USER"
    DB_PORT: "DB_PORT"
    DB_PASSWORD: "DB_PASSWORD"
    ENVIRONMENT: "test"
  #   NODEVERSION: "8.15.0"
  # parameter-store:
  #   DB_HOST: "DB_HOST"
  #   DB_NAME: "DB_NAME"
  #   DB_USER: "DB_USER"
  #   DB_PORT: "DB_PORT"
  #   DB_PASSWORD: "DB_PASSWORD"
  #   ENVIRONMENT: "test"

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - echo Starting the Install phase
      - node --version
      - npm --version
      - pwd

  build:
    commands:
      - echo "Running Build step"
      - echo Install NPM Packages
      - npm install
      - echo $DB_NAME
      - echo Running db migrations
      - ./node_modules/.bin/sequelize db:migrate

  post_build:
    commands:
      - echo Running post-build commands
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
